import copperA from '../images/offer_copper.jpg'
import copperB from '../images/offer_copper.jpg'
export const insights = [
    {title:'Nouvelle 1', date: '01.01.2024', type: 'nouvelle', link: copperA, brief: 'Le prix de cuivre a baisse', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 2', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Le prix de cuivre a augmente', src: '',
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 3', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'Ca marche', src: '', 
    description: ''},
    {title:'Nouvelle 4', date: '01.01.2024', type: 'insight', link: copperB, brief: 'bien', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 5', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'Voila', src: '',
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 6', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Ca marche', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 7', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'bien', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 8', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Voila', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 9', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'Voila', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 10', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Ca marche', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 11', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'Voila', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 12', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Ca marche', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 11', date: '01.01.2024', type: 'nouvelle', link: copperB, brief: 'Voila', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
    {title:'Nouvelle 12', date: '01.01.2024', type: 'insight', link: copperB, brief: 'Ca marche', src: '', 
    description: 'lalalalalalalalalalalalalalalaalalalalalalalalalaalalalalalala'},
]